### ISSUE TITLE
global.postMessage is not a function

### ISSUE THREAD

**Issue by akatiyar** [web-mech/peerjs-nodejs#2]
I got this error while running the example.

/workspace/node_modules/peerjs/lib/util.js:234
      global.postMessage(messageName, '*');
             ^

TypeError: global.postMessage is not a function
    at Object.setZeroTimeoutPostMessage [as setZeroTimeout] (/workspace/node_modules/peerjs/lib/util.js:234:14)
    at Peer.disconnect /workspace/node_modules/peerjs/lib/peer.js:420:8)
    at Socket.<anonymous> (/workspace/node_modules/peerjs/lib/peer.js:120:12)
    at Socket.emit (/workspace/node_modules/eventemitter3/index.js:71:35)
    at exports.XMLHttpRequest._http.onerror (/workspace/node_modules/peerjs/lib/socket.js:91:12)
    at exports.XMLHttpRequest.dispatchEvent (/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at exports.XMLHttpRequest.handleError (/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:533:10)
    at ClientRequest.errorHandler (/workspace/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)

**Comment by netlob** [comment]
Same here...

**Comment by r21meghashyam** [comment]
That's simple, write this:

global.postMessage=(message)=>{
    console.log(message);
}

**Comment by akatiyar** [comment]
For whatever reason, I am not seeing this issue anymore.  However, now I am getting following error.

/workspace/peerjs-nodejs/node_modules/js-binarypack/lib/bufferbuilder.js:54
    var builder = new BlobBuilder();
                  ^

TypeError: BlobBuilder is not a constructor
    at BufferBuilder.getBuffer (/workspace/peerjs-nodejs/node_modules/js-binarypack/lib/bufferbuilder.js:54:19)
    at Packer.getBuffer (/workspace/peerjs-nodejs/node_modules/js-binarypack/lib/binarypack.js:261:29)
    at Object.pack (/workspace/peerjs-nodejs/node_modules/js-binarypack/lib/binarypack.js:12:25)
    at DataConnection.send (/workspace/peerjs-nodejs/node_modules/peerjs/lib/dataconnection.js:171:21)

If I use JSON serialization, then I get following error. 

/workspace/peerjs-nodejs/node_modules/peerjs/lib/dataconnection.js:98
    if (datatype === Blob) {
                     ^

ReferenceError: Blob is not defined
    at DataConnection._handleDataMessage (/workspace/peerjs-nodejs/node_modules/peerjs/lib/dataconnection.js:98:22)

**Comment by r21meghashyam** [comment]
As the author has mentioned

> Binary data serialisation currently isn't supported with the current dependencies. ( probably still possible, just not as is). You must set the connection serialisation to either none or JSON

You cannot send blob content, send your data as JSON. You can provide your code snippet so that we can have a clear understanding of the problem.
